sudo: required
services:
    - docker

before_install:
    - docker-compose up --build -d
    - docker ps

script:
    - docker exec -ti director_backend ./manage.py test 
    - docker exec -ti director_frontend npm run test
