sudo: required
services:
    - docker

before_install:
    - echo "SPOTIPY_CLIENT_ID=$SPOTIPY_CLIENT_ID" >> backend/spotify.env
    - echo "SPOTIPY_CLIENT_SECRET=$SPOTIPY_CLIENT_SECRET" >> backend/spotify.env
    - echo "SPOTIPY_REDIRECT_URI=$SPOTIPY_REDIRECT_URI" >> backend/spotify.env
    - docker-compose up --build -d
    - docker ps

script:
    - docker exec -ti director_backend ./manage.py test 
    - docker exec -ti director_frontend npm run test
