version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: director_backend
    env_file:
      - backend/.env.dev
      - backend/spotify.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/director

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: director_frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/director-ui/
      - /director-ui/node_modules

volumes:
  backend:
