version: "3.7"

services:
  db:
    container_name: director_db
    image: postgres:11.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=director_db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=director_dev
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: director_redis
    image: redis:latest
    ports:
      - 6379:6379
      
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: director_backend
    depends_on:
      - db
    env_file:
      - backend/.env.dev
      - backend/spotify.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/director

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: director_frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=false
    ports:
      - 3000:3000
    volumes:
      - .:/director-ui/
      - /director-ui/node_modules

volumes:
  postgres:
  backend:
