# Generated by Django 3.0.3 on 2020-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_auto_20200220_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='request_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='join_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='skip_requests',
            field=models.ManyToManyField(blank=True, related_name='song_skips_requested', to='director.User'),
        ),
    ]
