# Generated by Django 3.0.3 on 2020-03-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyqueue',
            name='offset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
