# Generated by Django 3.0.3 on 2020-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
