# Generated by Django 3.0.3 on 2020-02-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.URLField(blank=True),
        ),
    ]
