# Generated by Django 3.0.3 on 2020-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_auto_20200220_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
