# Generated by Django 3.0.3 on 2020-02-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_auto_20200220_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(max_length=4, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.User')),
            ],
        ),
    ]
