# Generated by Django 3.0.3 on 2020-02-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='guests',
            field=models.ManyToManyField(related_name='guests', to='director.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='skipPercentageThreshold',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='party',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='director.User'),
        ),
        migrations.CreateModel(
            name='PartyQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ManyToManyField(related_name='history', to='director.SongRequest')),
                ('queue', models.ManyToManyField(related_name='queue', to='director.SongRequest')),
                ('skipped', models.ManyToManyField(related_name='skipped', to='director.SongRequest')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='queue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='director.PartyQueue'),
        ),
    ]
